package exceptionHandling;
/*
class UserDefinedException extends Exception
{
	public UserDefinedException(String s)
	{
		super(s);
	}
}
class TestException
{
    public static void main(String args[])
    {
        try {
            throw new UserDefinedException("UserDefinedException");
	}
	catch (UserDefinedException ex) 
        {
            System.out.println("Caught");
            System.out.println(ex.getMessage());
        }
    }
}
*/